### ISSUE TITLE
Il calorifero ovest automatico appare con il supporto in basso!!!

### ISSUE THREAD

**Issue by RAD750** [RAD750/RealEE#13]
![immagine](https://user-images.githubusercontent.com/12469744/51268351-354a7c80-19c0-11e9-87e8-d48ca4a1b7a5.png)
Come da immagine, il supporto del calorifero che dovrebbe stare nella parte superiore, appare in basso!

**Comment by lor54** [comment]
Risolto.

**Comment by RAD750** [comment]
Non è vero :warning: 
(bug presente in 1.2.6)

**Comment by lor54** [comment]
Risolto.
