### ISSUE TITLE
Lor il metano non funziona

### ISSUE THREAD

**Issue by cavaliere2122** [RAD750/RealEE#5]
Sistema il metano che fa cagare produce meno del  creosoto mordoso!!!! Nove e se lo fai magari prendi razione doppia

**Comment by lor54** [comment]
Forniscici possibilmente più informazioni @cavaliere2122, grazie.

**Comment by RAD750** [comment]
Fin quando non implementeremo qualcosa che consuma il metano, non possiamo aggiustare questo bug.
chiuso
