### ISSUE TITLE
Crafting dell'anemometro sbagliato

### ISSUE THREAD

**Issue by RAD750** [RAD750/RealEE#6]
Il crafting dovrebbe utilizzare dei **lingotti** di ferro, non dei cubi di ferro.

Se riesci, sarebbe anche meglio utilizzare un Electronic Circuit al posto del cubo di ferro esattamente sotto la bussola.

In pratica così:

`no lf no`
`lf bu lf`
`lf ec lf`

lf = lingotto di ferro
bu = bussola
no = niente
ec = circuito elettronico

**Comment by lor54** [comment]
Crafting corretto!
